#!/usr/bin/env python

# Copyright (C) 2014 Craig Phillips.  All rights reserved.

"""
A hashlib wrapper library to work around pylint errors generated by
hashlib's use of globals() to dynamically hoist openssl libraries into
its namespace.
"""

from __future__ import absolute_import

__all__ = ( "new" )

import hashlib

new = getattr(hashlib, "new", lambda x: None) # pylint: disable-msg=C0103
